#
#  Project Zomboid Dedicated Server using SteamCMD Docker Image.
#  Copyright (C) 2021-2022 Renegade-Master [renegade.master.dev@protonmail.com]
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

version: "3.8"

services:
  zomboid-dedicated-server:
    build:
      context: .
      dockerfile: docker/zomboid-dedicated-server.Dockerfile
    image: "docker.io/renegademaster/zomboid-dedicated-server:latest"
    container_name: zomboid-dedicated-server
    restart: "no"
    environment:
      ADMIN_PASSWORD: "changeme"
      ADMIN_USERNAME: "superuser"
      AUTOSAVE_INTERVAL: "15"
      BIND_IP: "0.0.0.0"
      DEFAULT_PORT: "16261"
      GAME_VERSION: "public"
      GC_CONFIG: "ZGC"
      MAP_NAMES: "Muldraugh, KY"
      MAX_PLAYERS: "16"
      MAX_RAM: "4096m"
      MOD_NAMES: ""
      MOD_WORKSHOP_IDS: ""
      PAUSE_ON_EMPTY: "true"
      PUBLIC_SERVER: "true"
      RCON_PASSWORD: "changeme_rcon"
      RCON_PORT: "27015"
      SERVER_NAME: "ZomboidServer"
      SERVER_PASSWORD: ""
      STEAM_VAC: "true"
      UDP_PORT: "16262"
      USE_STEAM: "true"
      TZ: "UTC"
    ports:
      - target: 16261
        published: 16261
        protocol: udp
      - target: 16262
        published: 16262
        protocol: udp
      - target: 27015
        published: 27015
        protocol: tcp
    volumes:
      - ./ZomboidDedicatedServer:/home/steam/ZomboidDedicatedServer
      - ./ZomboidConfig:/home/steam/Zomboid/
